### ISSUE TITLE
Clone trait for App

### ISSUE THREAD

**Issue by guitarhero17** [expl/rs-firebase-admin-sdk#6]
Hi @expl, thank you for this library.

I'm trying to use some provided methods (session cookie and id token verificators) as middleware extension of an Axum server. The idea is to create a session cookie based on a user id token coming from the frontend as a part of a login functionality. And subsequently verify that HttpOnly cookie for any authorized requests. Here is my structure:

```rs
// In firebase.rs

#[derive(Clone)]
pub struct FirebaseInstance {
    pub auth: FirebaseAuth<HyperApiClient<AuthenticationManager>>, // the trait `Clone` is not implemented
    pub token_verifier: LiveTokenVerifier<
        HttpCache<HyperClient<HttpsConnector<HttpConnector>>, BTreeMap<String, JwtRsaPubKey>>,
    >, // the trait `Clone` is not implemented
    pub firestore: FirestoreDb, // another library
    pub storage: Client, // another library
}


// In router.rs

pub fn create_routes(firebase_app: FirebaseInstance) -> Router {
  Router::new()
        .route(...)
        .layer(Extension(firebase_app))
  }
```

The problem arises from `axum::extension::Extension` requiring the argument to implement the `Clone` trait. Unfortunately, neither `FirebaseAuth`, nor  `LiveTokenVerifier` can be cloned. I also tried having an instance of `App<AuthenticationManager>` in the `FirebaseInstance` struct, but it too can not be "copied".

I'm new to Rust and I'd appreciate your help if you have any ideas how I can use an instance of `auth` or a `token_verifier` inside my Axum routes, so I can process the requests correctly.

Thank you for your insight!

**Comment by expl** [comment]
Hey @guitarhero17 , you can solve the cloning issue by putting the service/authenticator instances inside an [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html).

**Comment by guitarhero17** [comment]
Hi @expl, thank you for your help! The `Arc` pointer was exactly what I needed for the use case.
